[network_tls]
ca_cert = """
-----BEGIN CERTIFICATE-----\r
MIIBazCCARKgAwIBAgIIQ10OKhSEow0wCgYIKoZIzj0EAwIwITEfMB0GA1UEAwwW\r
cmNnZW4gc2VsZiBzaWduZWQgY2VydDAgFw03NTAxMDEwMDAwMDBaGA80MDk2MDEw\r
MTAwMDAwMFowITEfMB0GA1UEAwwWcmNnZW4gc2VsZiBzaWduZWQgY2VydDBZMBMG\r
ByqGSM49AgEGCCqGSM49AwEHA0IABKu4mUFsboxqTQLYNZr3o1bED9tBypnPeMGF\r
9cHZ1BJMJJ8QzJ7wGNtIFwNUrlbAKqA6PkhhxZADN6zv0V4tTDCjMjAwMB0GA1Ud\r
DgQWBBQNo4QUKg5dQ1Ng/ZNouGL81Kqw8jAPBgNVHRMBAf8EBTADAQH/MAoGCCqG\r
SM49BAMCA0cAMEQCIH05Mb10drPhuHPugxxyK3naXkhcbFpqcHJB4/FSh87JAiAc\r
x0C8BIXn8rI4yy6iKp9Dt1siAij6hf59Dx8QRp7k6A==\r
-----END CERTIFICATE-----\r
"""
cert = """
-----BEGIN CERTIFICATE-----\r
MIIBWjCCAQCgAwIBAgIJANgW8tOe4ybzMAoGCCqGSM49BAMCMCExHzAdBgNVBAMM\r
FnJjZ2VuIHNlbGYgc2lnbmVkIGNlcnQwIBcNNzUwMTAxMDAwMDAwWhgPNDA5NjAx\r
MDEwMDAwMDBaMCExHzAdBgNVBAMMFnJjZ2VuIHNlbGYgc2lnbmVkIGNlcnQwWTAT\r
BgcqhkjOPQIBBggqhkjOPQMBBwNCAAQKvRV/gCXes/bz2jg9PFZEeDlKAMtxBuWb\r
g9qF0E8CGWquMwIRXgcnUxwRdZu4gIfg4wRnt1b8uZaFD99lzWvkox8wHTAbBgNV\r
HREEFDASghB0ZXN0LWNoYWluLW5vZGUwMAoGCCqGSM49BAMCA0gAMEUCIQDYuYS3\r
SXkv+JX2GS5T9YzC0rEqO8dQvpEdSM+fd1X2yAIgXyeogDwnZIxStL+3LgAldvNp\r
KRsCHb+OZ93Kl3YMMNU=\r
-----END CERTIFICATE-----\r
"""
grpc_port = 51234
listen_port = 41234
priv_key = """
-----BEGIN PRIVATE KEY-----\r
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgYJlUB48YHEC4Gj+c\r
lnQq5u/9bZU4wKRv9mP/rA7/LtyhRANCAAQKvRV/gCXes/bz2jg9PFZEeDlKAMtx\r
BuWbg9qF0E8CGWquMwIRXgcnUxwRdZu4gIfg4wRnt1b8uZaFD99lzWvk\r
-----END PRIVATE KEY-----\r
"""
reconnect_timeout = 5

[[network_tls.peers]]
domain = 'test-chain-node1'
host = 'test-chain-node1-nodeport'
port = 40000

